### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by yusuke024** [nRewik/task-check-in#2]
I know that we told you that UI is not much of a concern, but can you make a small improvement on "Venue Detail View Controller"?

Some ideas here, replace text view with table view and display the information in the title-detail style or anything that would look appropriate. 
You may have some photos or a map of the venue in the table header.
You don't have to show everything returned by the API, just some that would be beneficial to the users.

**Comment by nRewik** [comment]
Yeah, will make it later tonight. After game researching 🎮
